# Generated by Django 3.1.7 on 2021-02-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210220_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.movie'),
        ),
    ]
